### ISSUE TITLE
[Vitória/ES] Desenvolvedor RubyOnRails Jr. Fullstack

### ISSUE THREAD

**Issue by LeandroSNunes** [eventplace/jobs#1]
## **Desenvolvedor RubyOnRails Jr. Fullstack | Eventplace**
O profissional irá trabalhar em um ambiente ágil contribuindo para o desenvolvimento de web apps de grande porte, participando desde a concepção até a entrega de features para os usuários.

**_Perfil_**
- Capacidade permanente de aprendizagem.
- Ter proatividade, organização e autonomia para evitar microgerenciamento.
- Boa comunicação para trabalhar em equipe.
- Comprometimento com entregas de features. 
- Estar trabalhando realmente com o que gosta.
- Encarar desafios como oportunidades.

**_Formação_**
- Curso superior (ou em andamento) em Ciência da Computação, Sistemas de Informação, Engenharia da Computação entre outras áreas correlacionadas.

**_Requisitos_**
- Ter trabalhado em projetos de desenvolvimento de web apps, independente da linguagem de programação.
- Habilidades para trabalhar com front-end (HTML5, SASS e Javascript).
- Conhecer bancos de dados relacionais.
- Habilidades básicas com Ruby e RubyOnRails.
- Utilizar o Git como controle de versão.
- Ter noções de desenvolvimento com testes automatizados (TDD e BDD).

**_Desejável_**
- Conhecer o Manifesto Ágil e metodologias como Scrum e XP.
- Desenvolvimento de web apps baseadas no 12factor.
- Ter perfil ativo no Github.
- Habilidades em Linux.
- Já ter ouvido as palavrinhas mágicas SOLID, DRY, KISS, YAGNI e SoC.
- Inglês básico.

**_Benefícios_**
- Horário de trabalho flexível
- Ambiente Startup
- Vale Alimentação
- Vale Transporte

**_Salário_**
- Entre R$ 2.500,00 à R$ 3.500,00 conforme experiência.

**_Contato_**
> **Envie seu currículo para dev@eventplace.me**

**Comment by Dimarchetti** [comment]
@LeandroSNunes Email enviado. Abraço.

**Comment by LeandroSNunes** [comment]
Ok @Dimarchetti
